"""
Django settings for commerce project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!71+8whlfrj=6zsxynl-af)g#*ul-x88qt_=@1wz36p(q(dt2w"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['*']  # Allows all hosts (⚠️ Only for testing!)
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shop.apps.ShopConfig",
    "django_daraja",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "commerce.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shop.context_processors.cart_count",
            ],
        },
    },
]

WSGI_APPLICATION = "commerce.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


MPESA_ENVIRONMENT = "sandbox"

MPESA_CONSUMER_KEY = "WHBx5igrXKq4jQhooZgg4YJkzGxn87ZUMr63teJ9oPS0h0Ay"
MPESA_CONSUMER_SECRET = (
    "t6FiOuoXYDkaj6GmKJN14WiJW3aJBaG3H2iBSvKHQIqArqgAQL9v22C0JAsIAyLw"
)

MPESA_SHORT_CODE = "174379"
MPESA_EXPRESS_SHORTCODE = "174379"

MPESA_SHORTCODE_TYPE = "till_number"

MPESA_PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"

MPESA_INITIATOR_USERNAME = "testapi"

MPESA_INITIATOR_SECURITY_CREDENTIALS = "Safaricom999!*!"

MPESA_CALLBACK_URL = "https://2d68-41-204-187-5.ngrok-free.app"


X_FRAME_OPTIONS = "SAMEORIGIN"


LOGIN_REDIRECT_URL = "/"  # Redirect to home page or any page after successful login

# Redirect after logout
LOGOUT_REDIRECT_URL = "/"  # Redirect to home page or any page after logging out

# URL to redirect to when the user is not authenticated and tries to access a protected view
LOGIN_URL = "/login/"  # This is where users will be redirected to log in
