# Generated by Django 5.2.1 on 2025-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='Hex color code, e.g. #FF0000', max_length=7, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='aliexpress_url',
            field=models.URLField(blank=True, help_text='AliExpress product page URL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. M, 42, 10cm x 5cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('aliexpress', 'AliExpress')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_contact',
            field=models.CharField(blank=True, help_text='Phone, email, or other contact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Name of local supplier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price from supplier', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.color'),
        ),
    ]
