# Generated by Django 5.2.1 on 2025-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_color_product_aliexpress_url_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Auto-generated stock keeping unit', max_length=100, null=True, unique=True),
        ),
    ]
