# Generated by Django 5.2.1 on 2025-06-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aliexpress_url',
            field=models.URLField(blank=True, help_text='AliExpress product page URL', max_length=5000, null=True),
        ),
    ]
