# Generated by Django 5.2 on 2025-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mpesatransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
