# Generated by Django 5.2 on 2025-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_mpesatransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_changed_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
