# Generated by Django 5.2 on 2025-04-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
