# Generated by Django 5.2 on 2025-04-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='signed_credential',
            field=models.TextField(blank=True, help_text='VC in JSON format, signed', null=True),
        ),
    ]
