# Generated by Django 5.2 on 2025-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_signed_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
